# Generated by Django 4.1.6 on 2023-12-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterNationalSpeakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='speakers/national_speakers/')),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NationalSpeakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='speakers/national_speakers/')),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
    ]
