# Generated by Django 4.2.7 on 2024-03-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0003_speaker_delete_internationalspeaker_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='spekaer_type',
            new_name='speaker_type',
        ),
    ]
