# Generated by Django 4.1.6 on 2023-12-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_remove_user_bio_user_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
    ]
