# Generated by Django 4.1.6 on 2024-01-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0016_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
