# Generated by Django 4.2.7 on 2024-03-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0020_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
