# Generated by Django 4.2.7 on 2024-03-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0023_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
