# Generated by Django 4.2.7 on 2024-03-08 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0026_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
