# Generated by Django 4.2.7 on 2024-03-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0027_auto_20240309_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='hamza', max_length=100, null=True),
        ),
    ]
