# Generated by Django 4.1.6 on 2024-01-22 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_livestream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 10, 14, 37, 619524, tzinfo=datetime.timezone.utc)),
        ),
    ]
