# Generated by Django 4.1.6 on 2024-01-22 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_livestream_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 10, 18, 16, 509113, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('live_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.livestream')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
