# Generated by Django 5.0.1 on 2024-01-27 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_message_user_alter_livestream_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 27, 12, 8, 30, 482922, tzinfo=datetime.timezone.utc)),
        ),
    ]
