# Generated by Django 5.0.1 on 2024-01-28 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_livestream_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('area', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], max_length=255)),
                ('designation', models.CharField(choices=[('Faculty', 'Faculty'), ('Student', 'Student'), ('Others', 'Others')], max_length=255)),
                ('faculty_designation', models.CharField(blank=True, choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=255, null=True)),
                ('affiliation', models.CharField(max_length=255)),
                ('fee_receipt', models.FileField(upload_to='fee_receipts')),
                ('registration_type', models.CharField(choices=[('Regular Registration', 'Regular Registration'), ('Student Registration', 'Student Registration')], max_length=255)),
                ('how_hear', models.CharField(choices=[('Social Media', 'Social Media'), ('Email', 'Email'), ('Word of Mouth', 'Word of Mouth'), ('Other', 'Other')], max_length=255)),
                ('purpose', models.CharField(choices=[('Abstract Submission', 'Abstract Submission'), ('Poster Submission', 'Poster Submission'), ('Only Attending', 'Only Attending')], max_length=255)),
                ('terms_and_conditions', models.BooleanField()),
                ('approved', models.CharField(choices=[('Approve', 'Approve'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 19, 35, 48, 320152, tzinfo=datetime.timezone.utc)),
        ),
    ]
