# Generated by Django 5.0.1 on 2024-01-28 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventregistration_alter_livestream_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 28, 19, 42, 3, 620807, tzinfo=datetime.timezone.utc)),
        ),
    ]
