# Generated by Django 5.0.1 on 2024-01-30 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventregistration_abstract_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='abstract_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='poster_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 17, 16, 18, 323591, tzinfo=datetime.timezone.utc)),
        ),
    ]
