# Generated by Django 5.0.1 on 2024-01-31 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_eventregistration_abstract_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 5, 21, 41, 522317, tzinfo=datetime.timezone.utc)),
        ),
    ]
