# Generated by Django 5.0.1 on 2024-01-31 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_livestream_start_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventRegistration',
            new_name='EventReg',
        ),
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 5, 40, 11, 260016, tzinfo=datetime.timezone.utc)),
        ),
    ]
