# Generated by Django 5.0.1 on 2024-01-31 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_rename_eventregistration_eventreg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 31, 5, 41, 58, 263671, tzinfo=datetime.timezone.utc)),
        ),
    ]
