# Generated by Django 4.2.7 on 2024-02-11 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_livestream_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 6, 22, 11, 620171, tzinfo=datetime.timezone.utc)),
        ),
    ]
