# Generated by Django 4.2.7 on 2024-02-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_livestream_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='time',
        ),
        migrations.AddField(
            model_name='speech',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
