# Generated by Django 4.2.7 on 2024-02-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_remove_speech_time_speech_end_time_speech_start_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purpose',
            new_name='Area',
        ),
        migrations.RenameModel(
            old_name='PurposeType',
            new_name='SubArea',
        ),
    ]
