# Generated by Django 4.2.7 on 2024-03-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0004_rename_spekaer_type_speaker_speaker_type'),
        ('events', '0032_rename_purpose_area_rename_purposetype_subarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakers.speaker'),
        ),
    ]
