# Generated by Django 4.2.7 on 2024-03-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_alter_speech_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='speaker',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
