# Generated by Django 4.2.7 on 2024-04-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_heading',
            field=models.CharField(default='What is RTNS', max_length=100),
        ),
    ]
