# Generated by Django 4.2.7 on 2024-04-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutus_about_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='patronimage',
            name='patron_heading',
            field=models.CharField(default='Our Patrons', max_length=100),
        ),
    ]
