# Generated by Django 4.2.7 on 2024-04-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patron_delete_patronimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='patron_type',
            field=models.CharField(default='Patron', max_length=100),
        ),
    ]
