# Generated by Django 4.2.7 on 2024-02-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('area', models.CharField(max_length=20)),
                ('registration_type', models.CharField(choices=[('regular_reg', 'Regular Registration'), ('student_reg', 'Student Registration')], max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('faculty_designation', models.CharField(max_length=20)),
                ('affiliation', models.CharField(max_length=100)),
                ('fee_receipt_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fee_receipt', models.FileField(blank=True, null=True, upload_to='fee_receipts')),
                ('how_here', models.CharField(max_length=100)),
                ('reg_purpose', models.CharField(max_length=20)),
                ('abstract_name', models.CharField(blank=True, max_length=100)),
                ('abstract_type', models.CharField(blank=True, choices=[('oralpresentation', 'Oral presentation'), ('posterpresentation', 'Poster presentation')], max_length=20)),
                ('abstract_category', models.CharField(blank=True, choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('bio', 'Biology')], max_length=20)),
                ('file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=200)),
                ('poster_title', models.CharField(blank=True, max_length=100)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('approveforposter', 'Approved for poster'), ('approveforpresentation', 'Approved for presentation')], default='pending', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
