# Generated by Django 4.2.7 on 2024-02-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_reg', '0002_area_subarea_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subarea',
            old_name='purpose',
            new_name='area',
        ),
    ]
