# Generated by Django 4.2.7 on 2024-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department_logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/header/department_logos')),
            ],
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('year', models.IntegerField(default=2024)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('sponsor_logo', models.ImageField(upload_to='images/footer')),
            ],
        ),
        migrations.CreateModel(
            name='header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtns_logo', models.ImageField(upload_to='images/header')),
                ('title', models.CharField(default='International Conference on Recent Trends in Natural Sciences', max_length=100)),
                ('department_logos', models.ManyToManyField(related_name='headers', to='partials.department_logos')),
            ],
        ),
    ]
