# Generated by Django 4.2.7 on 2024-04-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0004_remove_header_department_logos_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='footer',
        ),
        migrations.RemoveField(
            model_name='header',
            name='department_logo',
        ),
    ]
