# Generated by Django 4.2.7 on 2024-04-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0005_delete_footer_remove_header_department_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=4)),
                ('year', models.IntegerField(default=2024)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('sponsor_logo', models.ImageField(upload_to='images/footer')),
            ],
        ),
    ]
