# Generated by Django 4.2.7 on 2024-04-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0006_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.EmailField(default='rtns@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='footer',
            name='sponsor_logo',
            field=models.ImageField(default='static/Image/ue.png', upload_to='images/footer'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='title',
            field=models.CharField(default='RTNS', max_length=4),
        ),
        migrations.AlterField(
            model_name='header',
            name='rtns_logo',
            field=models.ImageField(default='static/Image/RTNSlogo.png', upload_to='images/header'),
        ),
    ]
