# Generated by Django 4.2.7 on 2024-04-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0008_rename_footer_websitefooter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentlogo',
            name='logo',
            field=models.ImageField(upload_to='header/department_logos'),
        ),
        migrations.AlterField(
            model_name='websiteheader',
            name='rtns_logo',
            field=models.ImageField(default='static/Image/RTNSlogo.png', upload_to='header'),
        ),
    ]
