# Generated by Django 4.1.6 on 2023-12-23 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_speech_time'),
        ('article', '0002_alter_article_article_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
    ]
