# Generated by Django 4.1.6 on 2023-12-26 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_remove_profile_email_remove_profile_full_name_and_more'),
        ('article', '0005_article_article_file_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.profile'),
        ),
    ]
