# Generated by Django 4.1.6 on 2024-01-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
