# Generated by Django 4.2.7 on 2024-04-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='department_logos',
            field=models.ManyToManyField(blank=True, limit_choices_to={'headers__isnull': True}, related_name='headers', to='partials.department_logos'),
        ),
    ]
