# Generated by Django 4.2.7 on 2024-04-01 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0002_alter_header_department_logos'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/header/department_logos')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partials.header')),
            ],
        ),
        migrations.DeleteModel(
            name='Department_logos',
        ),
        migrations.AlterField(
            model_name='header',
            name='department_logos',
            field=models.ManyToManyField(blank=True, related_name='headers', to='partials.departmentlogo'),
        ),
    ]
