# Generated by Django 4.2.7 on 2024-04-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0003_departmentlogo_delete_department_logos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='department_logos',
        ),
        migrations.AddField(
            model_name='header',
            name='department_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_association', to='partials.departmentlogo'),
        ),
        migrations.AlterField(
            model_name='departmentlogo',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_logos', to='partials.header'),
        ),
    ]
