# Generated by Django 4.2.7 on 2024-04-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partials', '0007_alter_footer_email_alter_footer_sponsor_logo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footer',
            new_name='WebsiteFooter',
        ),
        migrations.RenameModel(
            old_name='header',
            new_name='WebsiteHeader',
        ),
    ]
